FROM nginx
RUN apt-get update
RUN apt-get install -y httpd
RUN apt-get clean all -y
RUN apt-get install -y httpd
RUN apt-get clean all -y
RUN apt-get install -y httpd
RUN apt-get clean all -y
RUN apt-get install -y httpd
RUN apt-get clean all -y
RUN apt-get install -y httpd
RUN apt-get clean all -y
RUN apt-get install -y httpd
RUN apt-get clean all -y
