FROM nginx
RUN yum update
RUN yum install -y httpd
RUN yum clean all -y
RUN yum install -y httpd
RUN yum clean all -y
RUN yum install -y httpd
RUN yum clean all -y
RUN yum install -y httpd
RUN yum clean all -y
RUN yum install -y httpd
RUN yum clean all -y
RUN yum install -y httpd
RUN yum clean all -y
