FROM nginx
RUN apt-get update && \
    apt-get install -y curl  && \
    apt-get clean all -y  && \
    apt-get install -y curl  && \
    apt-get clean all -y  && \
    apt-get install -y curl  && \
    apt-get clean all -y  && \
    apt-get install -y curl  && \
    apt-get clean all -y  && \
    apt-get install -y curl  && \
    apt-get clean all -y  && \
    apt-get install -y curl  && \
    apt-get clean all -y

