apiVersion: v1
kind: Pod
metadata:
 name: busybox1-pvc
spec:
 containers:
 - name: busybox
   image: busybox
   command: ["/bin/sh"]
   args: ["-c", "while true; do echo hello; sleep 10;done"]
   volumeMounts:
   - mountPath: /data
     name: my-volume
 volumes:
 - name: my-volume
   persistentVolumeClaim:
     claimName: pvc-15g